console.log('Hello')
console.log(typeof('234'))
console.log(typeof(234))
console.log(234234)
console.log("alsdkfjlasdfj")
console.log(234.342)
console.log('My Favourite Number: 9')
console.log(typeof('My Favourite Number: 9'))
console.log('My Favourite Number:' + 54)
console.log(typeof('My Favourite Number: +54'))
console.log(5+5)